# Generated by Django 5.2.5 on 2025-08-31 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='period',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Отчетный период'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statisticsshort',
            name='period',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01', verbose_name='Отчетный период'),
            preserve_default=False,
        ),
    ]
