# Generated by Django 5.2.5 on 2025-08-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_statistics_period_statisticsshort_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='mo',
            name='area',
            field=models.TextField(default='Волгоградская область', verbose_name='Округ'),
            preserve_default=False,
        ),
    ]
