# Generated by Django 5.2.5 on 2025-08-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mo_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mo',
            name='population',
        ),
        migrations.AlterField(
            model_name='mo',
            name='href',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='mo',
            name='path_class',
            field=models.CharField(blank=True, max_length=200, verbose_name='Техническое поле'),
        ),
        migrations.AlterField(
            model_name='mo',
            name='path_fill',
            field=models.CharField(blank=True, max_length=200, verbose_name='цвет заполнения'),
        ),
    ]
