# Generated by Django 5.2.5 on 2025-08-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_mo_population_alter_mo_href_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo',
            name='href',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mo',
            name='path_class',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Техническое поле'),
        ),
        migrations.AlterField(
            model_name='mo',
            name='path_d',
            field=models.TextField(blank=True, null=True, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='mo',
            name='path_description_data',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mo',
            name='path_description_data_img',
            field=models.ImageField(blank=True, null=True, upload_to='MO/', verbose_name='Изображение МО'),
        ),
        migrations.AlterField(
            model_name='mo',
            name='path_fill',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='цвет заполнения'),
        ),
    ]
