# Generated by Django 5.2.1 on 2025-09-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mo_href_alter_mo_path_class_alter_mo_path_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsshort',
            name='F',
            field=models.FloatField(verbose_name='Коэффициент финансовой доступности'),
        ),
    ]
