# Generated by Django 5.2.1 on 2025-09-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_statisticsshort_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='F',
            field=models.FloatField(verbose_name='Коэффициент финансовой доступности'),
        ),
    ]
