# Generated by Django 5.2.1 on 2025-09-01 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_statisticsshort_mo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsshort',
            name='MO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mo', verbose_name='Муниципальное образование второго уровня'),
        ),
    ]
