# Generated by Django 5.2.1 on 2025-09-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_statisticsshort_mo'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsshort',
            name='CHN',
            field=models.FloatField(default='1', help_text='Численность населения', verbose_name='Население'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statisticsshort',
            name='FG',
            field=models.FloatField(default=1, verbose_name='Коэффициент финансовой грамотности'),
            preserve_default=False,
        ),
    ]
