# Generated by Django 5.2.1 on 2025-09-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_statisticsshort_chn_statisticsshort_fg'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsshort',
            name='CHN_Sub',
            field=models.FloatField(default=1, help_text='Численность населения', verbose_name='Население'),
            preserve_default=False,
        ),
    ]
