# Generated by Django 5.2.1 on 2025-09-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_statisticsshort_chn_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsshort',
            name='Pop_Per',
            field=models.FloatField(default=1, help_text='Численность населения', verbose_name='Население'),
            preserve_default=False,
        ),
    ]
