# Generated by Django 5.2.5 on 2025-09-03 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_statisticsshort_pop_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='MO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mo_name', to='core.mo', verbose_name='МО'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ai_checked_status',
            field=models.CharField(blank=True, choices=[('ai_checked_true', 'Проверено ИИ'), ('ai_cancelled', 'Отменено ИИ'), ('ai_checked_in_progress', 'В процессе проверки'), ('ai_checked_false', 'Не проверено')], default='ai_checked_false', max_length=30, null=True, verbose_name='Статус ИИ'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], null=True, verbose_name='Оценка'),
        ),
    ]
