# Generated by Django 5.2.1 on 2025-09-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_review_mo_alter_review_ai_checked_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mo',
            options={'verbose_name': 'Муниципальное образование', 'verbose_name_plural': 'Муниципальные образования'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв/предложение', 'verbose_name_plural': 'Список обращений'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['description'], 'verbose_name': 'Сервис', 'verbose_name_plural': 'Список сервисов'},
        ),
        migrations.AlterModelOptions(
            name='statisticsshort',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'отчеты'},
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Текст обращения'),
        ),
    ]
