# Generated by Django 5.2.1 on 2025-09-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_mo_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(default=1, verbose_name='автор ссобщения'),
            preserve_default=False,
        ),
    ]
