# Generated by Django 5.2.1 on 2025-09-05 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_review_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Текст ответа')),
                ('answer_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('answer_is_published', models.BooleanField(blank=True, default=True, null=True, verbose_name='Опубликован')),
                ('answer_author', models.CharField(verbose_name='автор ответа')),
                ('Review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_id', to='core.review', verbose_name='Идентификатор обращения')),
            ],
        ),
    ]
