# Generated by Django 5.2.1 on 2025-09-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_reviewanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Список обращений'},
        ),
        migrations.AlterModelOptions(
            name='reviewanswer',
            options={'verbose_name': 'Ответ на обращение', 'verbose_name_plural': 'Ответы на обращение'},
        ),
    ]
