# Generated by Django 5.2.1 on 2025-09-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_review_options_alter_reviewanswer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewanswer',
            options={'verbose_name': 'Ответ на обращение', 'verbose_name_plural': 'Ответы на обращения'},
        ),
    ]
